# Generated by Django 6.1.1 on 2026-09-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientpartner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientPartner',
        ),
    ]
