# Generated by Django 4.2.30 on 2026-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_leadership_and_blog_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_label', models.CharField(help_text='Short name on the slide tab, e.g. "Cloud"', max_length=40)),
                ('tab_icon', models.CharField(default='fas fa-bolt', help_text='Font Awesome class for the tab', max_length=50)),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above the title', max_length=80)),
                ('title', models.CharField(help_text='Main headline, e.g. "Smart IT Solutions for"', max_length=120)),
                ('highlight', models.CharField(blank=True, help_text='Gradient words shown after the title, e.g. "Modern Businesses"', max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Wide background image (1920×1080 or larger). Leave empty for a designed gradient background.', upload_to='hero_slides/')),
                ('primary_label', models.CharField(blank=True, max_length=40, verbose_name='Primary button label')),
                ('primary_url', models.CharField(blank=True, max_length=300, verbose_name='Primary button link')),
                ('secondary_label', models.CharField(blank=True, max_length=40, verbose_name='Secondary button label')),
                ('secondary_url', models.CharField(blank=True, max_length=300, verbose_name='Secondary button link')),
                ('accent', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order'],
            },
        ),
    ]
