# Generated by Django 4.2.30 on 2026-09-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='nav_badge',
            field=models.CharField(blank=True, choices=[('', 'None'), ('new', 'New'), ('popular', 'Popular')], max_length=10, verbose_name='Navbar badge'),
        ),
        migrations.AddField(
            model_name='service',
            name='nav_description',
            field=models.CharField(blank=True, help_text='One line shown in the navbar. Defaults to the short description.', max_length=160, verbose_name='Navbar description'),
        ),
        migrations.AddField(
            model_name='service',
            name='nav_label',
            field=models.CharField(blank=True, help_text='Optional shorter name for the navbar. Defaults to the service title.', max_length=60, verbose_name='Navbar label'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_nav',
            field=models.BooleanField(default=True, verbose_name='Show in navbar'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='nav_description',
            field=models.CharField(blank=True, help_text='One line shown in the navbar. Defaults to the short description.', max_length=160, verbose_name='Navbar description'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='nav_label',
            field=models.CharField(blank=True, help_text='Optional shorter name for the navbar. Defaults to the category name.', max_length=60, verbose_name='Navbar label'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='show_in_nav',
            field=models.BooleanField(default=True, verbose_name='Show in navbar'),
        ),
    ]
