# Generated by Django 4.2.30 on 2026-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_navbar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefit_items',
            field=models.JSONField(blank=True, default=list, help_text='[{"title", "text"}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, help_text='[{"question", "answer"}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='feature_items',
            field=models.JSONField(blank=True, default=list, help_text='[{"icon", "title", "text"}]'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_items',
            field=models.JSONField(blank=True, default=list, help_text='[{"title", "text"}]'),
        ),
        migrations.AlterField(
            model_name='service',
            name='faq',
            field=models.TextField(blank=True, help_text='Legacy JSON FAQs (superseded by faq_items).'),
        ),
    ]
